project_id = "uheeddmtntnlgrpzfjph"

[functions.send-notification]
enabled = true
verify_jwt = true
entrypoint = "./functions/send-notification/index.ts"

[functions.notify-feedback]
enabled = true
verify_jwt = true
entrypoint = "./functions/notify-feedback/index.ts"
